# Generated by Django 3.2.7 on 2021-10-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
